LANGUAGES = {
    "en": {
        # General
        "welcome": "👋 Welcome to *Money Manager Bot*!\n\nI help you track income & expenses, set financial goals, monitor currencies, and view financial statistics.\n\nIf you interested in new updates and receive feedback you can check this channel: @lookatpatch\n\nPlease choose your language / Выберите язык:",
        "language_set": "✅ Language set to *English*.",
        "webcode_sent": "🔑 Your web login code: `{code}`\n\nValid for 10 minutes, single-use. Enter it on the dashboard's login page.",
        "webcode_sent_with_link": "🔑 Your web login code: `{code}`\n\nValid for 10 minutes, single-use.\n\n👉 [Open the dashboard]({url})",
        "web_logout": "Log out",
        "web_nav_dashboard": "Overview",
        "web_nav_forecast": "Forecast",
        "web_net_worth": "Net worth",
        "web_incomplete_rates": "Some balances couldn't be converted (rates unavailable) — total may be incomplete.",
        "web_all": "All",
        "web_date_from": "From",
        "web_date_to": "To",
        "web_apply": "Apply",
        "web_truncated_note": "Showing the first {n} — narrow the date range to see more.",
        "web_balance": "Balance",
        "web_no_chart_data": "Not enough data for this period.",
        "web_seen_months": "seen in {months} months, last on {date}",
        "web_recurring_forecast": "Estimated recurring spend next month",
        "web_forecast_current": "Current net worth",
        "web_forecast_monthly_net": "Average monthly net (last 90 days)",
        "web_forecast_projection": "In {months} months, if nothing changes",
        "web_forecast_no_data": "Not enough data for a forecast yet.",
        "main_menu": "🏠 *Main Menu*\n\nWhat would you like to do?",
        "back": "⬅️ Back",
        "cancel": "❌ Cancel",
        "btn_yes": "✅ Yes",
        "btn_no": "❌ No",
        "cancelled": "❌ Cancelled.",
        "error": "⚠️ Something went wrong. Please try again.",
        "invalid_amount": "⚠️ Invalid amount. Please enter a positive number (e.g. 150.50).",
        "invalid_input": "⚠️ Invalid input. Please try again.",

        # Menu buttons
        "btn_transactions": "💸 Transactions",
        "btn_goals": "🎯 Goals",
        "btn_currencies": "💱 Currencies",
        "btn_statistics": "📊 Statistics",
        "btn_settings": "⚙️ Settings",
        "btn_accounts": "🏦 Accounts",
        "btn_budgets": "📐 Budgets",
        "btn_add_income": "➕ Add Income",
        "btn_add_expense": "➖ Add Expense",
        "btn_view_transactions": "📋 View Transactions",
        "btn_clear_transactions": "🗑️ Clear All",
        "btn_delete_transaction": "🗑 Delete Transaction",
        "btn_add_goal": "🎯 Add Goal",
        "btn_view_goals": "📋 View Goals",
        "btn_delete_goal": "🗑️ Delete Goal",
        "btn_convert_goal": "💱 Convert Goal Currency",

        # Accounts
        "accounts_menu_header": "🏦 *Accounts*\n\nManage your bank cards, crypto wallets, and cash.",
        "btn_add_account": "➕ Add Account",
        "btn_view_accounts": "📋 View Accounts",
        "btn_delete_account": "🗑️ Delete Account",
        "btn_import_csv": "📥 Import Statement (CSV)",
        "choose_account_type": "🏦 Choose account type:",
        "account_type_bank": "🏦 Bank / Card",
        "account_type_crypto": "₿ Crypto Exchange",
        "account_type_cash": "💵 Cash",
        "enter_account_name": "📝 Enter account name (e.g. *Kaspi*, *Binance*, *Wallet*):",
        "enter_account_currency": "💱 Choose currency for this account:",
        "enter_account_balance": "💰 Enter your *current balance* on this account (e.g. 150000.00):",
        "account_saved": "✅ Account added!\n\n*{name}* ({type})\nBalance: {balance} {currency}",
        "no_accounts": "📭 No accounts yet.\n\n⚠️ You need to add at least one account before creating transactions.",
        "no_accounts_for_transaction": "⚠️ *You have no accounts yet!*\n\nPlease add an account first (bank card, crypto exchange or cash) — then you can record income and expenses.",
        "accounts_header": "🏦 *Your Accounts:*\n\n",
        "account_line": "{emoji} *{name}* ({type})\n   Balance: `{balance:.2f} {currency}`\n\n",
        "choose_account_to_delete": "Choose an account to delete:\n\n⚠️ All transactions linked to it will be unlinked.",
        "account_deleted": "🗑️ Account deleted.",
        "choose_account_for_transaction": "🏦 Choose account for this transaction:",

        # Budgets
        "budgets_menu_header": "📐 *Budgets*\n\nSet a monthly spending limit per category and get warned before you blow it.",
        "btn_set_budget": "➕ Set Budget",
        "btn_view_budgets": "📋 View Budgets",
        "btn_delete_budget": "🗑️ Delete Budget",
        "no_budgets": "📭 No budgets set yet.",
        "choose_budget_category": "🏷️ Choose a category to budget for:\n_(✅ = already has a budget, will be replaced)_",
        "enter_budget_amount": "💵 Enter the *monthly* budget amount for *{category}*\n_(in your base currency)_:",
        "budget_saved": "✅ Budget set!\n\n*{category}*: {amount} {currency} / month",
        "budgets_header": "📐 *Your Monthly Budgets:*\n\n",
        "budget_line": "*{category}*\n{bar} {pct}%\nSpent: `{spent} / {amount} {currency}`\n\n",
        "choose_budget_to_delete": "🗑 Choose a budget to delete:",
        "budget_deleted": "🗑️ Budget deleted.",
        "budget_exceeded": "🚨 *Budget exceeded!*\n{category}: {spent}/{amount} {currency} ({pct}% this month)",
        "budget_near_limit": "⚠️ *Budget warning:* {category} is at {pct}% ({spent}/{amount} {currency} this month)",

        # Transactions
        "choose_transaction_type": "Choose transaction type:",
        "enter_amount": "💵 Enter the amount:",
        "enter_currency": "💱 Choose currency:",
        "enter_category": "🏷️ Choose a category:",
        "enter_description": "📝 Enter a short description (or /skip):",
        "transaction_saved": "✅ Transaction saved!\n\n*Type:* {type}\n*Account:* {account}\n*Amount:* {amount} {currency}\n*Category:* {category}\n*Description:* {description}",
        "income": "Income",
        "expense": "Expense",
        "no_transactions": "📭 No transactions yet.",
        "confirm_clear_transactions": "⚠️ *Are you sure?*\n\nThis will delete ALL your transactions. This action cannot be undone!",
        "transactions_cleared": "✅ All transactions cleared!\n\nDeleted: {count} transaction(s)",
        "transactions_header": "📋 *Recent Transactions (last 20):*\n\n",
        "transaction_line": "{emoji} `{date}` — *{amount} {currency}* [{category}] 🏦{account} _{description}_\n",
        "choose_transaction_to_delete": "🗑 *Choose a transaction to delete:*\n_(showing last 20)_",
        "transaction_deleted": "✅ Transaction deleted. Goal progress recalculated.",
        "recalculating_goals": "⏳ Deleting and recalculating goals…",

        # Categories
        "cat_food": "🍔 Food",
        "cat_transport": "🚗 Transport",
        "cat_housing": "🏠 Housing",
        "cat_health": "💊 Health",
        "cat_entertainment": "🎉 Entertainment",
        "cat_salary": "💼 Salary",
        "cat_freelance": "💻 Freelance",
        "cat_investment": "📈 Investment",
        "cat_gift": "🎁 Gift",
        "cat_loan_payment": "🏦 Loan Payment",
        "cat_other": "📦 Other",

        "btn_edit_goal": "✏️ Edit Target Amount",
        "choose_goal_to_edit": "✏️ *Choose a goal to edit:*",
        "enter_new_goal_amount": "✏️ *{title}*\nCurrent target: `{current_target} {currency}`\n\nEnter the new target amount:",
        "goal_target_updated": "✅ Goal updated!\n\n*{title}*\nNew target: `{new_target} {currency}`\nProgress: `{current}` / `{new_target} {currency}` ({pct}%)\n{status}",

        # Goals
        "choose_goal_type": "Choose goal type:",
        "goal_type_save": "💰 Save up",
        "goal_type_repay": "🏦 Repay a loan/debt",
        "enter_goal_title": "📝 Enter goal title (e.g. 'Buy a car', 'Pay off loan'):",
        "enter_goal_amount": "💵 Enter the target amount:",
        "enter_goal_currency": "💱 Choose a currency for this goal:",
        "enter_goal_deadline": "📅 Enter deadline (YYYY-MM-DD) or /skip:",
        "goal_saved": "✅ Goal created!\n\n*{title}*\nTarget: {amount} {currency}\nDeadline: {deadline}\n\n📊 Starting progress: {initial} ({pct}%)",
        "no_goals": "📭 No goals set yet.",
        "goals_header": "🎯 *Your Goals:*\n\n",
        "goal_line": "{n}. *{title}* ({type})\n   Progress: {current}/{target} {currency} ({pct}%)\n   Deadline: {deadline}\n\n",
        "goal_completed": "🎉 *Congratulations! Goal completed!*",
        "goal_progress_updated": "Goal progress updated",
        "choose_goal_to_delete": "Choose a goal to delete:",
        "goal_deleted": "🗑️ Goal deleted.",
        "choose_goal_to_convert": "Choose a goal to convert currency:",
        "choose_new_currency": "Choose new currency for this goal:",
        "goal_converted": "✅ Goal currency converted!\n\n*{title}*\nNew target: {amount} {currency}",

        # Currencies
        "currencies_header": "💱 *Live Market Rates*\n_(base: USD)_\n\n",
        "fiat_rates": "📌 *Fiat Currencies:*\n{rates}\n",
        "crypto_rates": "₿ *Cryptocurrencies:*\n{rates}\n",
        "metals_rates": "🥇 *Metals (per troy oz):*\n{rates}\n",
        "fetching_rates": "⏳ Fetching live rates...",
        "rates_error": "⚠️ Could not fetch some rates. Please try again later.",
        "rates_incomplete_note": "⚠️ _Some amounts couldn't be converted (rates unavailable) — this total may be incomplete._",

        # Statistics
        "stats_header": "📊 *Your Financial Statistics*\n\n",
        "stats_balance": "💰 *Balance:* {balance} {currency}\n",
        "stats_income": "📈 *Total Income:* {amount} {currency}\n",
        "stats_expense": "📉 *Total Expenses:* {amount} {currency}\n",
        "stats_by_category": "\n🏷️ *Expenses by Category:*\n{breakdown}",
        "stats_no_data": "📭 No data yet. Start adding transactions!",

        # Settings
        "settings_header": "⚙️ *Settings*",
        "btn_change_language": "🌐 Change Language",
        "btn_change_currency": "💵 Base Currency",
        "base_currency_set": "✅ Base currency set to *{currency}*.",
        "choose_base_currency": "Choose your base display currency:",

        # Languages
        "choose_language": "🌐 Choose language:",

        # Statistics / Charts
        "stats_choose_period": "📊 *Statistics*\n\nChoose a time period:",
        "stats_period_week":   "📅 This Week",
        "stats_period_month":  "🗓 This Month",
        "stats_period_6m":     "📆 6 Months",
        "stats_period_year":   "🗓 This Year",
        "stats_period_custom": "✏️ Custom Range",
        "stats_generating":    "⏳ Generating charts…",
        "stats_period_header": "📊 *Statistics: {period}*\n\n",
        "stats_no_data_period": "No transactions in this period.",
        "stats_no_charts":     "No data to display charts.",
        "stats_choose_charts":     "📊 *Choose charts to display:*\n\nToggle on/off, then tap Generate.",
        "stats_generate":          "▶️ Generate",
        "stats_no_chart_selected": "Select at least one chart type.",
        "stats_enter_start_date": "📅 Enter *start date* (YYYY-MM-DD):",
        "stats_enter_end_date":   "📅 Enter *end date* (YYYY-MM-DD):",
        "stats_invalid_date":     "⚠️ Invalid date. Use format YYYY-MM-DD (e.g. 2024-01-15).",
        "stats_end_before_start": "⚠️ End date must be after start date.",

        # Recurring / forecast
        "stats_recurring": "🔁 Recurring & Forecast",
        "no_recurring": "📭 No recurring expenses detected yet.\n\n_(needs spending in the same category across at least 2 of the last 3 months)_",
        "recurring_header": "🔁 *Recurring Expenses*\n_(detected from your last 90 days)_\n\n",
        "recurring_line": "*{category}*: ~{amount} {currency}/mo\n_seen in {months} months, last on {last_date}_\n\n",
        "recurring_forecast": "📊 *Estimated recurring spend next month:* {amount} {currency}",

        # Net worth forecast
        "btn_forecast": "📈 Forecast",
        "forecast_generating": "⏳ Calculating forecast…",
        "forecast_no_data": "📭 Not enough data yet — add some accounts and transactions first.",
        "forecast_header": "📈 *Net Worth Forecast*\n_(based on your last 90 days)_\n\n",
        "forecast_current": "💰 Current net worth: {amount} {currency}\n",
        "forecast_monthly_net_positive": "📈 Average monthly net: +{amount} {currency}\n",
        "forecast_monthly_net_negative": "📉 Average monthly net: {amount} {currency}\n",
        "forecast_projection": "\n🔮 In {months} months, if nothing changes: *{amount} {currency}*",

        # CSV statement import
        "import_choose_account": "Choose which account to import transactions into:",
        "import_send_file": "Send the CSV file exported from your bank or card statement.\n\nI'll auto-detect the date, amount and description columns — most bank exports work as-is.",
        "import_wrong_file_type": "⚠️ Please send a .csv file.",
        "import_parse_error_file_too_large": "⚠️ File is too large (max 2 MB).",
        "import_parse_error_unreadable_encoding": "⚠️ Couldn't read this file's text encoding. Export it as UTF-8 CSV and try again.",
        "import_parse_error_empty_file": "⚠️ The file is empty.",
        "import_parse_error_unrecognized_columns": "⚠️ Couldn't find date/amount columns. Supported headers: Date, Amount (or Debit + Credit).",
        "import_parse_error_too_many_rows": "⚠️ Too many rows (max 5000). Split the export into smaller files.",
        "import_parse_error_generic": "⚠️ Couldn't parse this file.",
        "import_no_valid_rows": "📭 No valid transactions found in this file.",
        "import_preview": "📄 *Import preview*\n\nFound: {found} transactions ({income} income, {expense} expense)\nAlready imported (skipped as duplicates): {duplicates}\nCouldn't parse: {errors}\n\nImport {to_import} transactions into *{account}*?",
        "import_confirm_btn": "✅ Import",
        "import_done": "✅ Imported {count} transactions into *{account}*.",

        # Chart captions / titles
        "chart_goals_title":   "Goals Progress",
        "chart_goals_caption": "🎯 *Goal Progress*",
        "chart_pie_title":     "Expenses by Category",
        "chart_pie_caption":   "🥧 *Expenses by Category*",
        "chart_bar_title":     "Income vs Expenses",
        "chart_bar_caption":   "📊 *Income vs Expenses*",
    },

    "ru": {
        # General
        "welcome": "👋 Добро пожаловать в *Money Manager Bot*!\n\nЯ помогаю отслеживать доходы и расходы, ставить финансовые цели, мониторить курсы валют и просматривать финансовую статистику.\n\nЕсли вас интересуют обновления и вы хотите обратной связи, можете зайти на канал: @lookatpatch\n\nПожалуйста, выберите язык / Please choose your language:",
        "language_set": "✅ Язык установлен: *Русский*.",
        "webcode_sent": "🔑 Код для входа в веб-версию: `{code}`\n\nДействует 10 минут, одноразовый. Введите его на странице входа.",
        "webcode_sent_with_link": "🔑 Код для входа в веб-версию: `{code}`\n\nДействует 10 минут, одноразовый.\n\n👉 [Открыть веб-версию]({url})",
        "web_logout": "Выйти",
        "web_nav_dashboard": "Обзор",
        "web_nav_forecast": "Прогноз",
        "web_net_worth": "Общий капитал",
        "web_incomplete_rates": "Часть балансов не удалось конвертировать (курсы недоступны) — итог может быть неполным.",
        "web_all": "Все",
        "web_date_from": "С",
        "web_date_to": "По",
        "web_apply": "Применить",
        "web_truncated_note": "Показаны первые {n} — сузьте период, чтобы увидеть больше.",
        "web_balance": "Баланс",
        "web_no_chart_data": "Недостаточно данных за этот период.",
        "web_seen_months": "встречалось {months} мес., последний раз {date}",
        "web_recurring_forecast": "Прогноз регулярных расходов на следующий месяц",
        "web_forecast_current": "Текущий капитал",
        "web_forecast_monthly_net": "Средний чистый результат в месяц (за 90 дней)",
        "web_forecast_projection": "Через {months} мес., если ничего не изменится",
        "web_forecast_no_data": "Пока недостаточно данных для прогноза.",
        "main_menu": "🏠 *Главное меню*\n\nЧто вы хотите сделать?",
        "back": "⬅️ Назад",
        "cancel": "❌ Отмена",
        "btn_yes": "✅ Да",
        "btn_no": "❌ Нет",
        "cancelled": "❌ Отменено.",
        "error": "⚠️ Что-то пошло не так. Попробуйте ещё раз.",
        "invalid_amount": "⚠️ Неверная сумма. Введите положительное число (например, 150.50).",
        "invalid_input": "⚠️ Неверный ввод. Попробуйте ещё раз.",

        # Menu buttons
        "btn_transactions": "💸 Транзакции",
        "btn_goals": "🎯 Цели",
        "btn_currencies": "💱 Валюты",
        "btn_statistics": "📊 Статистика",
        "btn_settings": "⚙️ Настройки",
        "btn_accounts": "🏦 Счета",
        "btn_budgets": "📐 Бюджеты",
        "btn_add_income": "➕ Добавить доход",
        "btn_add_expense": "➖ Добавить расход",
        "btn_view_transactions": "📋 История транзакций",
        "btn_clear_transactions": "🗑️ Удалить все",
        "btn_delete_transaction": "🗑 Удалить транзакцию",
        "btn_add_goal": "🎯 Добавить цель",
        "btn_view_goals": "📋 Мои цели",
        "btn_delete_goal": "🗑️ Удалить цель",
        "btn_convert_goal": "💱 Конвертировать валюту цели",

        # Accounts
        "accounts_menu_header": "🏦 *Счета*\n\nУправляйте банковскими картами, криптокошельками и наличными.",
        "btn_add_account": "➕ Добавить счёт",
        "btn_view_accounts": "📋 Мои счета",
        "btn_delete_account": "🗑️ Удалить счёт",
        "btn_import_csv": "📥 Импорт выписки (CSV)",
        "choose_account_type": "🏦 Выберите тип счёта:",
        "account_type_bank": "🏦 Банк / Карта",
        "account_type_crypto": "₿ Криптобиржа",
        "account_type_cash": "💵 Наличные",
        "enter_account_name": "📝 Введите название счёта (например, *Kaspi*, *Binance*, *Кошелёк*):",
        "enter_account_currency": "💱 Выберите валюту счёта:",
        "enter_account_balance": "💰 Введите ваш *текущий баланс* на этом счёте (например, 150000.00):",
        "account_saved": "✅ Счёт добавлен!\n\n*{name}* ({type})\nБаланс: {balance} {currency}",
        "no_accounts": "📭 Счетов пока нет.\n\n⚠️ Добавьте хотя бы один счёт, прежде чем создавать транзакции.",
        "no_accounts_for_transaction": "⚠️ *У вас пока нет счетов!*\n\nСначала добавьте счёт (банковская карта, криптобиржа или наличные) — только после этого можно добавлять доходы и расходы.",
        "accounts_header": "🏦 *Ваши счета:*\n\n",
        "account_line": "{emoji} *{name}* ({type})\n   Баланс: `{balance:.2f} {currency}`\n\n",
        "choose_account_to_delete": "Выберите счёт для удаления:\n\n⚠️ Все транзакции, привязанные к нему, будут отвязаны.",
        "account_deleted": "🗑️ Счёт удалён.",
        "choose_account_for_transaction": "🏦 Выберите счёт для этой транзакции:",

        # Budgets
        "budgets_menu_header": "📐 *Бюджеты*\n\nУстановите месячный лимит расходов по категории и получайте предупреждение, когда приближаетесь к нему.",
        "btn_set_budget": "➕ Установить бюджет",
        "btn_view_budgets": "📋 Мои бюджеты",
        "btn_delete_budget": "🗑️ Удалить бюджет",
        "no_budgets": "📭 Бюджетов пока нет.",
        "choose_budget_category": "🏷️ Выберите категорию для бюджета:\n_(✅ = бюджет уже есть, будет заменён)_",
        "enter_budget_amount": "💵 Введите *месячный* лимит бюджета для *{category}*\n_(в вашей базовой валюте)_:",
        "budget_saved": "✅ Бюджет установлен!\n\n*{category}*: {amount} {currency} / месяц",
        "budgets_header": "📐 *Ваши месячные бюджеты:*\n\n",
        "budget_line": "*{category}*\n{bar} {pct}%\nПотрачено: `{spent} / {amount} {currency}`\n\n",
        "choose_budget_to_delete": "🗑 Выберите бюджет для удаления:",
        "budget_deleted": "🗑️ Бюджет удалён.",
        "budget_exceeded": "🚨 *Бюджет превышен!*\n{category}: {spent}/{amount} {currency} ({pct}% за этот месяц)",
        "budget_near_limit": "⚠️ *Внимание, бюджет:* {category} — {pct}% ({spent}/{amount} {currency} за этот месяц)",

        # Transactions
        "choose_transaction_type": "Выберите тип транзакции:",
        "enter_amount": "💵 Введите сумму:",
        "enter_currency": "💱 Выберите валюту:",
        "enter_category": "🏷️ Выберите категорию:",
        "enter_description": "📝 Введите краткое описание (или /skip):",
        "transaction_saved": "✅ Транзакция сохранена!\n\n*Тип:* {type}\n*Счёт:* {account}\n*Сумма:* {amount} {currency}\n*Категория:* {category}\n*Описание:* {description}",
        "income": "Доход",
        "expense": "Расход",
        "no_transactions": "📭 Транзакций пока нет.",
        "confirm_clear_transactions": "⚠️ *Вы уверены?*\n\nЭто удалит ВСЕ ваши транзакции. Это действие невозможно отменить!",
        "transactions_cleared": "✅ Все транзакции удалены!\n\nУдалено: {count} транзакция(й)",
        "transactions_header": "📋 *Последние транзакции (до 20):*\n\n",
        "transaction_line": "{emoji} `{date}` — *{amount} {currency}* [{category}] 🏦{account} _{description}_\n",
        "choose_transaction_to_delete": "🗑 *Выберите транзакцию для удаления:*\n_(последние 20)_",
        "transaction_deleted": "✅ Транзакция удалена. Прогресс целей пересчитан.",
        "recalculating_goals": "⏳ Удаление и пересчёт целей…",

        # Categories
        "cat_food": "🍔 Еда",
        "cat_transport": "🚗 Транспорт",
        "cat_housing": "🏠 Жильё",
        "cat_health": "💊 Здоровье",
        "cat_entertainment": "🎉 Развлечения",
        "cat_salary": "💼 Зарплата",
        "cat_freelance": "💻 Фриланс",
        "cat_investment": "📈 Инвестиции",
        "cat_gift": "🎁 Подарок",
        "cat_loan_payment": "🏦 Погашение кредита",
        "cat_other": "📦 Другое",

        # Goals
        "choose_goal_type": "Выберите тип цели:",
        "goal_type_save": "💰 Накопить сбережения",
        "goal_type_repay": "🏦 Погасить кредит/долг",
        "enter_goal_title": "📝 Введите название цели (например, 'Купить машину', 'Закрыть кредит'):",
        "enter_goal_amount": "💵 Введите целевую сумму:",
        "enter_goal_currency": "💱 Выберите валюту для этой цели:",
        "enter_goal_deadline": "📅 Введите дедлайн (ГГГГ-ММ-ДД) или /skip:",
        "goal_saved": "✅ Цель создана!\n\n*{title}*\nЦель: {amount} {currency}\nДедлайн: {deadline}\n\n📊 Начальный прогресс: {initial} ({pct}%)",
        "no_goals": "📭 Целей пока нет.",
        "goals_header": "🎯 *Ваши цели:*\n\n",
        "goal_line": "{n}. *{title}* ({type})\n   Прогресс: {current}/{target} {currency} ({pct}%)\n   Дедлайн: {deadline}\n\n",
        "goal_completed": "🎉 *Поздравляем! Цель достигнута!*",
        "goal_progress_updated": "Прогресс целей обновлён",
        "choose_goal_to_delete": "Выберите цель для удаления:",
        "goal_deleted": "🗑️ Цель удалена.",
        "choose_goal_to_convert": "Выберите цель для конвертации валюты:",
        "choose_new_currency": "Выберите новую валюту для этой цели:",
        "goal_converted": "✅ Валюта цели конвертирована!\n\n*{title}*\nНовая цель: {amount} {currency}",
        "btn_edit_goal": "✏️ Изменить целевую сумму",
        "choose_goal_to_edit": "✏️ *Выберите цель для редактирования:*",
        "enter_new_goal_amount": "✏️ *{title}*\nТекущая цель: `{current_target} {currency}`\n\nВведите новую целевую сумму:",
        "goal_target_updated": "✅ Цель обновлена!\n\n*{title}*\nНовая цель: `{new_target} {currency}`\nПрогресс: `{current}` / `{new_target} {currency}` ({pct}%)\n{status}",

        # Currencies
        "currencies_header": "💱 *Курсы в реальном времени*\n_(база: USD)_\n\n",
        "fiat_rates": "📌 *Фиатные валюты:*\n{rates}\n",
        "crypto_rates": "₿ *Криптовалюты:*\n{rates}\n",
        "metals_rates": "🥇 *Металлы (за тройскую унцию):*\n{rates}\n",
        "fetching_rates": "⏳ Получение актуальных курсов...",
        "rates_error": "⚠️ Не удалось получить некоторые курсы. Попробуйте позже.",
        "rates_incomplete_note": "⚠️ _Часть сумм не удалось конвертировать (курсы недоступны) — итог может быть неполным._",

        # Statistics
        "stats_header": "📊 *Ваша финансовая статистика*\n\n",
        "stats_balance": "💰 *Баланс:* {balance} {currency}\n",
        "stats_income": "📈 *Общий доход:* {amount} {currency}\n",
        "stats_expense": "📉 *Общие расходы:* {amount} {currency}\n",
        "stats_by_category": "\n🏷️ *Расходы по категориям:*\n{breakdown}",
        "stats_no_data": "📭 Данных пока нет. Начните добавлять транзакции!",

        # Settings
        "settings_header": "⚙️ *Настройки*",
        "btn_change_language": "🌐 Изменить язык",
        "btn_change_currency": "💵 Базовая валюта",
        "base_currency_set": "✅ Базовая валюта установлена: *{currency}*.",
        "choose_base_currency": "Выберите базовую валюту для отображения:",

        # Languages
        "choose_language": "🌐 Выберите язык:",

        # Статистика / Графики
        "stats_choose_period": "📊 *Статистика*\n\nВыберите период:",
        "stats_period_week":   "📅 Эта неделя",
        "stats_period_month":  "🗓 Этот месяц",
        "stats_period_6m":     "📆 6 месяцев",
        "stats_period_year":   "🗓 Этот год",
        "stats_period_custom": "✏️ Свой период",
        "stats_generating":    "⏳ Генерирую графики…",
        "stats_period_header": "📊 *Статистика: {period}*\n\n",
        "stats_no_data_period": "Транзакций за этот период нет.",
        "stats_no_charts":     "Данных для графиков нет.",
        "stats_choose_charts":     "📊 *Выберите графики:*\n\nВключите/выключите нужные и нажмите Генерировать.",
        "stats_generate":          "▶️ Генерировать",
        "stats_no_chart_selected": "Выберите хотя бы один тип графика.",
        "stats_enter_start_date": "📅 Введите *начальную дату* (ГГГГ-ММ-ДД):",
        "stats_enter_end_date":   "📅 Введите *конечную дату* (ГГГГ-ММ-ДД):",
        "stats_invalid_date":     "⚠️ Неверный формат даты. Используйте ГГГГ-ММ-ДД (например, 2024-01-15).",
        "stats_end_before_start": "⚠️ Конечная дата должна быть позже начальной.",

        # Регулярные платежи / прогноз
        "stats_recurring": "🔁 Регулярные платежи и прогноз",
        "no_recurring": "📭 Регулярные платежи пока не обнаружены.\n\n_(нужны траты в одной категории минимум в 2 из последних 3 месяцев)_",
        "recurring_header": "🔁 *Регулярные расходы*\n_(за последние 90 дней)_\n\n",
        "recurring_line": "*{category}*: ~{amount} {currency}/мес\n_встречалось {months} мес., последний раз {last_date}_\n\n",
        "recurring_forecast": "📊 *Прогноз регулярных расходов на следующий месяц:* {amount} {currency}",

        # Прогноз капитала
        "btn_forecast": "📈 Прогноз",
        "forecast_generating": "⏳ Считаю прогноз…",
        "forecast_no_data": "📭 Пока недостаточно данных — сначала добавьте счета и операции.",
        "forecast_header": "📈 *Прогноз общего капитала*\n_(на основе последних 90 дней)_\n\n",
        "forecast_current": "💰 Текущий капитал: {amount} {currency}\n",
        "forecast_monthly_net_positive": "📈 Средний доход в месяц: +{amount} {currency}\n",
        "forecast_monthly_net_negative": "📉 Средний результат в месяц: {amount} {currency}\n",
        "forecast_projection": "\n🔮 Через {months} мес., если ничего не изменится: *{amount} {currency}*",

        # Импорт выписки CSV
        "import_choose_account": "Выберите счёт, в который импортировать операции:",
        "import_send_file": "Отправьте CSV-файл выписки из банка или карты.\n\nЯ сам определю столбцы с датой, суммой и описанием — большинство банковских выгрузок подходят как есть.",
        "import_wrong_file_type": "⚠️ Пришлите файл в формате .csv.",
        "import_parse_error_file_too_large": "⚠️ Файл слишком большой (максимум 2 МБ).",
        "import_parse_error_unreadable_encoding": "⚠️ Не удалось прочитать кодировку файла. Сохраните выписку в UTF-8 CSV и попробуйте снова.",
        "import_parse_error_empty_file": "⚠️ Файл пустой.",
        "import_parse_error_unrecognized_columns": "⚠️ Не удалось найти столбцы с датой/суммой. Поддерживаемые заголовки: Date/Дата, Amount/Сумма (или Debit+Credit/Расход+Приход).",
        "import_parse_error_too_many_rows": "⚠️ Слишком много строк (максимум 5000). Разбейте выписку на файлы поменьше.",
        "import_parse_error_generic": "⚠️ Не удалось разобрать файл.",
        "import_no_valid_rows": "📭 В файле не найдено ни одной подходящей операции.",
        "import_preview": "📄 *Предпросмотр импорта*\n\nНайдено: {found} операций (доход: {income}, расход: {expense})\nУже были импортированы (пропущено как дубликаты): {duplicates}\nНе удалось распознать: {errors}\n\nИмпортировать {to_import} операций в *{account}*?",
        "import_confirm_btn": "✅ Импортировать",
        "import_done": "✅ Импортировано {count} операций в *{account}*.",

        # Подписи к графикам
        "chart_goals_title":   "Прогресс целей",
        "chart_goals_caption": "🎯 *Прогресс целей*",
        "chart_pie_title":     "Расходы по категориям",
        "chart_pie_caption":   "🥧 *Расходы по категориям*",
        "chart_bar_title":     "Доходы и расходы",
        "chart_bar_caption":   "📊 *Доходы и расходы*",
    }
}


def t(lang: str, key: str, **kwargs) -> str:
    """Get translated string."""
    text = LANGUAGES.get(lang, LANGUAGES["en"]).get(key, LANGUAGES["en"].get(key, key))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, ValueError):
            pass
    return text


def category_label(category_key: str, lang: str) -> str:
    """Translate a canonical category key (e.g. 'food') into a display label.

    Falls back to returning the value unchanged for anything that isn't a
    known key — covers transactions/budgets recorded before the bot stored
    canonical keys, when the category text itself was already the label.
    Shared by bot.py and webapp.py so both ever have exactly one notion of
    what a category key displays as.
    """
    label = t(lang, f"cat_{category_key}")
    return category_key if label == f"cat_{category_key}" else label
